language: python
python: 3.6
dist: bionic
compiler: clang
sudo: required
addons:
   apt:
      packages:
         - python3-all
         - python3-all-dev
         - libeigen3-dev
         - libhdf5-serial-dev
         - libboost-all-dev
         - libgts-dev
         - pybind11-dev
         - cmake
         - cmake-data
         - ninja-build
         - libvtk6-dev
         - libdouble-conversion-dev # for building minieigen11
before_install:
    - sudo add-apt-repository -y ppa:nschloe/pybind11-backports
    - sudo apt-get -q update
    - sudo apt-get -y install pybind11-dev
install:
   - pip3 install xlrd xlwt-future numpy colorama genshi psutil pillow h5py lockfile ipython colour_runner xlsxwriter prettytable setuptools matplotlib git+https://github.com/eudoxos/minieigen11
script:
   - mkdir -p build
   - cd build
   - cmake -GNinja -DWOO_FLAVOR="" -DWOO_DEBUG=OFF -DWOO_PYBIND11=ON -DWOO_VTK=ON -DWOO_HDF5=ON -DWOO_GTS=ON -DWOO_QT5=OFF -DWOO_OPENMP=ON -DWOO_CCACHE=OFF -DWOO_CLANG=ON ..
   - ninja install
   - timeout 60 woo --test
